language: c
addons:
  postgresql: 9.3
before_install:
  - sudo apt-get update
  - sudo apt-get install -qq bzr mr
  - mr up
install: sudo apt-get install -qq postgresql-plpython-9.3 postgresql-plpython3-9.3 python python-setuptools python3 python3-setuptools
env:
  matrix:
    - PYTHON=python
    - PYTHON=python3
script: $PYTHON setup.py test
